#!make
# Makefile for Nezumi
# $Id: configure 499 2006-04-07 20:19:37Z MagicalTux $
# This file is automatically generated. There's no point trying to modify it !

# Following values are master values. Any change will have effect on the whole compilation process.
SVN = $(shell cat .svn/entries 2>/dev/null | grep revision | head -n 1 | sed -e 's/^[^"]*"//;s/"[^"]*$$//')
CC = /usr/bin/gcc
AR = /usr/bin/ar
CFLAGS = -pipe -Wall --std=c99 -g -ggdb -I/cygdrive/c/f/src/include -I/cygdrive/c/f/src/ -DSVN_REVISION=$(SVN).0
LDFLAGS = 
LIBS = -L/cygdrive/c/f/src/lib -lz -lm
BUILD_TO = POSIX

export MAKE CC AR CFLAGS LIBS SVN LDFLAGS BUILD_TO

all: title  common login char ladmin tool map addons

.PHONY: common login char ladmin tool map addons   txt txt-win32 sql title

title:
	@echo "Nezumi Ragnarok Emulator"
	@echo "#Nezumi @ irc.ooKoo.org"
	@echo
	@echo "Compiling Nezumi v1.1.0 (SVN#$(SVN))"
	@echo

common: 
	@echo -e " - DIR\tsrc/common"
	@$(MAKE) --no-print-directory -C src/common/ libcommon.a

login:  common
	@echo -e " - DIR\tsrc/login"
	@$(MAKE) --no-print-directory -C src/login/ ../../login-server.exe

char:  common
	@echo -e " - DIR\tsrc/char"
	@$(MAKE) --no-print-directory -C src/char/ ../../char-server.exe

ladmin:  common
	@echo -e " - DIR\tsrc/ladmin"
	@$(MAKE) --no-print-directory -C src/ladmin/ ../../ladmin.exe

tool:  common
	@echo -e " - DIR\tsrc/tool"
	@$(MAKE) --no-print-directory -C src/tool/ 

map:  common
	@echo -e " - DIR\tsrc/map"
	@$(MAKE) --no-print-directory -C src/map/ ../../map-server.exe

addons:  common
	@echo -e " - DIR\tsrc/addons"
	@$(MAKE) --no-print-directory -C src/addons/ 

clean: 
	@$(MAKE) -C src/common/ clean
	@$(MAKE) -C src/login/ clean
	@$(MAKE) -C src/char/ clean
	@$(MAKE) -C src/ladmin/ clean
	@$(MAKE) -C src/tool/ clean
	@$(MAKE) -C src/map/ clean
	@$(MAKE) -C src/addons/ clean



txt:
	./configure --with-make

txt-win32:
	./configure --with-win32 --with-make

sql:
	./configure --with-mysql --with-make

sql-win32:
	./configure --with-win32 --with-mysql --with-make

sqlite:
	./configure --with-sqlite --with-make

sqlite-win32:
	./configure --with-win32 --with-sqlite --with-make

