#!make
# Makefile for Nezumi
# $Id: configure 517 2006-04-09 09:49:29Z Harbin $
# This file is automatically generated. There's no point trying to modify it !

# Following values are master values. Any change will have effect on the whole compilation process.
SVN = $(shell cat .svn/entries 2>/dev/null | grep revision | head -n 1 | sed -e 's/^[^"]*"//;s/"[^"]*$$//')
CC = /usr/bin/gcc
AR = /usr/bin/ar
CFLAGS = -pipe -Wall --std=c99 -g -ggdb -I/home/nezumidev/src/include -I/home/nezumidev/src/ -I/usr/include/mysql -DSVN_REVISION=$(SVN).0
LDFLAGS = 
LIBS = -L/home/nezumidev/src/lib -L/usr/lib -lcrypt -lnsl -lmysqlclient -ldl -lz -lm
BUILD_TO = POSIX

export MAKE CC AR CFLAGS LIBS SVN LDFLAGS BUILD_TO

all: title  common db_mysql login char_sql login_txt-converter ladmin map addons

.PHONY: common db_mysql login char_sql login_txt-converter ladmin map addons   txt txt-win32 sql title

title:
	@echo "Nezumi Ragnarok Emulator"
	@echo "#Nezumi @ irc.ooKoo.org"
	@echo
	@echo "Compiling Nezumi v1.1.0 (SVN#$(SVN)) (MySQL)"
	@echo

common: 
	@echo -e " - DIR\tsrc/common"
	@$(MAKE) --no-print-directory -C src/common/ libcommon.a

db_mysql:  common
	@echo -e " - DIR\tsrc/db_mysql"
	@$(MAKE) --no-print-directory -C src/db_mysql/ libdb_mysql.a

login:  common db_mysql
	@echo -e " - DIR\tsrc/login"
	@$(MAKE) --no-print-directory -C src/login/ ../../login-server

char_sql:  common db_mysql
	@echo -e " - DIR\tsrc/char_sql"
	@$(MAKE) --no-print-directory -C src/char_sql/ ../../char-server

login_txt-converter:  common db_mysql
	@echo -e " - DIR\tsrc/login_txt-converter"
	@$(MAKE) --no-print-directory -C src/login_txt-converter/ ../../login-converter

ladmin:  common db_mysql
	@echo -e " - DIR\tsrc/ladmin"
	@$(MAKE) --no-print-directory -C src/ladmin/ ../../ladmin

map:  common db_mysql
	@echo -e " - DIR\tsrc/map"
	@$(MAKE) --no-print-directory -C src/map/ ../../map-server

addons:  common db_mysql
	@echo -e " - DIR\tsrc/addons"
	@$(MAKE) --no-print-directory -C src/addons/ 

clean: 
	@$(MAKE) -C src/common/ clean
	@$(MAKE) -C src/db_mysql/ clean
	@$(MAKE) -C src/login/ clean
	@$(MAKE) -C src/char_sql/ clean
	@$(MAKE) -C src/login_txt-converter/ clean
	@$(MAKE) -C src/ladmin/ clean
	@$(MAKE) -C src/map/ clean
	@$(MAKE) -C src/addons/ clean



txt:
	./configure --with-make

txt-win32:
	./configure --with-win32 --with-make

sql:
	./configure --with-mysql --with-make

sql-win32:
	./configure --with-win32 --with-mysql --with-make

sqlite:
	./configure --with-sqlite --with-make

sqlite-win32:
	./configure --with-win32 --with-sqlite --with-make

